
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog, messagebox, Label

# Acoustic Modelling Modules
from modules.CleanUp import CleanUp
from modules.WaveManip import WaveManip

###


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


# Button Commands and Manipulation ######################


def browse_files():
    try:
        filename = filedialog.askopenfilename(initialdir=".",
                                              title="Select a File",
                                              filetypes=(("WAVE file",
                                                          "*.wav*"),
                                                         ("MP3 file",
                                                          "*.mp3*")))
        # Change label contents
        entry_1.configure(text="File Opened: " + filename)
        try:
            run_model(filename)
        except:
            messagebox.showerror('Python Error', 'No file selected')
    except Exception as error:
        messagebox.showerror('Python Error', error)


def run_model(stream: str):
    CleanUp(stream).convert()
    wave_form = WaveManip(stream).wave_plot()
    canvas.itemconfig(image_2, image_image_2.configure(file=wave_form))


######################################################


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("750x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 750,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    375.0,
    250.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=browse_files,
    relief="flat"
)
button_1.place(
    x=657.0,
    y=19.0,
    width=78.0,
    height=28.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    329.0,
    33.0,
    image=entry_image_1
)
entry_1 = Label(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=14.0,
    y=19.0,
    width=630.0,
    height=26.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    221.0,
    232.0,
    image=image_image_2
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=14.0,
    y=419.0,
    width=78.0,
    height=28.0
)
window.resizable(False, False)
window.mainloop()
